### ISSUE TITLE
can i train my custom dataset now?

### ISSUE THREAD

**Issue by YanqingWu** [sevakon/efficientdet#2]

**Comment by sevakon** [comment]
Hey YanqingWu!
Thank you for your issue.
I am currently working on training on COCO dataset from scratch since reproducing paper results is my first priority. When I am done with this task, it will be relatively easy to integrate training on other datasets. 
I will leave this issue open to let you know when everything will be ready.

**Comment by YanqingWu** [comment]
@sevakon thanks

**Comment by YanqingWu** [comment]
i am curiosity why you can train with coco, but there are many bugs when i train my custom data

**Comment by YanqingWu** [comment]
i have saw your code for bifpn, maybe you forget something ?
it should be another p_6_2?

```python
        if len(features) == 5:
            p_3, p_4, p_5, p_6, p_7 = features
            p_4_2, p_5_2 = None, None
        else:
            p_3, p_4, p_4_2, p_5, p_5_2, p_6, p_7 = features
```

**Comment by sevakon** [comment]
the short answer is no, this is not a bug. 
P_6 feature map is obtained from the last feature map of efficientnet backbone by applying 1x1 convolution to adjust the number of channels to the bifpn width, and then maxpooling is applied to get a two times smaller spatial dimension. 
such behavior corresponds to the official implementation by google in the automl repository

**Comment by YanqingWu** [comment]
are you give up this project?
@sevakon

**Comment by sevakon** [comment]
hey @YanqingWu !
Thank you for your interest!
No, I did not give up the project, just focusing on the workload in the uni for now. Hopefully, I will have some spare time on Sunday to finish EffDet.
